In [5]:
import torch
from torch import cuda, jit

In [3]:
torch.ByteTensor(1)

tensor([4], dtype=torch.uint8)

In [4]:
torch.cuda.set_rng_state_all(new_state=(torch.ByteTensor(1)))

TypeError: set_rng_state_all() got an unexpected keyword argument 'new_state'

In [2]:
torch.__version__

'1.5.0'

In [8]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x)

    def weighted_kernel_sum(self, weight):
        return weight * self.conv.weight


n = Net()
example_weight = torch.rand(1, 1, 3, 3)
example_forward_input = torch.rand(1, 1, 3, 3)

# Trace a specific method and construct `ScriptModule` with
# a single `forward` method
module = torch.jit.trace(n.forward, example_forward_input)

# Trace a module (implicitly traces `forward`) and construct a
# `ScriptModule` with a single `forward` method
module = torch.jit.trace(n, example_forward_input)

# Trace specific methods on a module (specified in `inputs`), constructs
# a `ScriptModule` with `forward` and `weighted_kernel_sum` methods
inputs = {'forward' : example_forward_input, 'weighted_kernel_sum' : example_weight}
module = torch.jit.trace_module(n, example_inputs=inputs)

TypeError: trace_module() got an unexpected keyword argument 'example_inputs'

In [12]:
src = torch.tensor([[4, 3, 5],
                        [6, 7, 8]])
torch.take(src, index=torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [13]:
rates = torch.rand(4, 4) * 5 
torch.poisson(input=rates)

tensor([[0., 0., 0., 1.],
        [3., 3., 1., 1.],
        [2., 4., 3., 1.],
        [0., 0., 4., 1.]])

In [14]:

rates = torch.rand(4, 4) * 5 
torch.poisson(rates, torch.Generator())

tensor([[0., 2., 6., 0.],
        [0., 4., 1., 0.],
        [3., 3., 2., 9.],
        [0., 2., 2., 0.]])

In [16]:
a = torch.randn(4)
torch.add(a, other=20, value=1)

TypeError: add() got an unexpected keyword argument 'value'

In [17]:
a = torch.randn(4)
torch.clamp(a, max=0.5, value =1)

TypeError: clamp() got an unexpected keyword argument 'value'

In [20]:
A = torch.randn(2, 3, 3)
b = torch.randn(2, 3, 1)
A_LU = torch.lu(A)
x = torch.lu_solve(b=b, *A_LU)

SyntaxError: invalid syntax (<ipython-input-20-aa012d6621f0>, line 4)

In [25]:
a = torch.randn(3)
torch.mul(a, other=100, value=100)

TypeError: mul() got an unexpected keyword argument 'value'