<a href="https://colab.research.google.com/github/eagle1234321/eagle/blob/main/rule_13_tf_bug_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow_io==0.15.0 tensorflow==2.3.0 

In [6]:
import tensorflow as tf
import tensorflow_io as tfio
import numpy as np

input = np.array(
    [[[[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,],],
    [[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,],],
    [[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,]]]]
)

input_uint8 = tf.cast(input, tf.uint8)
print(input_uint8)
encoded_file = tfio.image.encode_gif(input_uint8)
input_decoded = tf.io.decode_gif(encoded_file)
print(input_decoded)

tf.Tensor(
[[[[ 13  54  87]
   [ 56 210 195]
   [230 135  61]]

  [[ 13  54  87]
   [ 56 210 195]
   [230 135  61]]

  [[ 13  54  87]
   [ 56 210 195]
   [230 135  61]]]], shape=(1, 3, 3, 3), dtype=uint8)
tf.Tensor(
[[[[  8  48  80]
   [ 56 208 192]
   [224 128  56]]

  [[  8  48  80]
   [ 56 208 192]
   [224 128  56]]

  [[  8  48  80]
   [ 56 208 192]
   [224 128  56]]]], shape=(1, 3, 3, 3), dtype=uint8)
